### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by OlegZavrazhin** [RickCogley/RCC-Hugo2015#8]
gulp.parallel is not a function
gulp.registry is not a function
gulp.series is not a function
etc.

How to fix it?

**Comment by RickCogley** [comment]
@OlegZavrazhin, this repo is part of my overall dev environment, and is not meant to be self contained. I'm not sure what could be wrong, but, I've heard of gulp version problems causing errors like that. You might look into that.

**Comment by RickCogley** [comment]
When I do `npm run task` this screenshot shows what I get: 

https://drive.google.com/open?id=0B3E_g6R5WF8Ab3ZrUVVwVXRnMzQ

**Comment by OlegZavrazhin** [comment]
Thanks, I've solved it
